primenet.py: main loop: Enable testing url request and responses
primenet.py: merge_config_and_options: update local.ini with num_cache=0
primenet.py: main loop: write local.ini
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":54458639, "worktype":"LL", "res64":"40F68C6AEE0948C0", "fft-length":3145728, "shift-count":2735528, "error-code":"00000000", "program":{"name":"Mlucas", "version":"19.0"}, "timestamp":"2020-05-06 02:35:03 GMT", "aid":"EB967319D07F653DB43185F33D561A6A"}
primenet.py: submit_one_line_v5: Result correctly send to server: assignment_id=EB967319D07F653DB43185F33D561A6A
primenet.py: submit_one_line_v5: server message: CPU credit is 0.2553 GHz-days.
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":8419067, "known-factors":["12056575411753"], "worktype":"PRP-3", "res64":"9944C4309DB464EB", "residue-type":5, "res2048":"B2C5D0483FAE11AD995550ADB138456E23DE7927636452245638856CD781BB285F218E9A87329AFC153F65DBF1974418FBC554A019C1597B80F2A676548910EAEE59CE51BCD64C8EAAACE76808AD58F2C9C0E75446FABDE3B6800C65BCD236694C9FCCA79A4B4073D378C81FE37BAF2B91BC2DA4879B9AF49EEAFB3183439930F47D720F77F62553E4231ABC39B0B085A380A2F1A00925C1D8E692A87CEFE078B7487415F890E614CBD9D2C438682B19DAF773D3CE3491F9E0483CC9D2E1145691573408D866F102A84DA00587B6C4A847A0810ECE89389F9BB859DD30EA5629AF2975D512A059B5EAA96EA6BD3705A98F79E8DC8244CAAF9944C4309DB464EB", "fft-length":458752, "shift-count":6484152, "error-code":"00000000", "security-code":"94558A0A", "program":{"name":"Prime95", "version":"29.8", "build":6, "port":8}, "timestamp":"2020-05-24 02:20:45", "errors":{"gerbicz":0}, "aid":"CFBD5DE31FDE86596171ADFCD25BE803"}
primenet.py: submit_one_line_v5: Result correctly send to server: assignment_id=CFBD5DE31FDE86596171ADFCD25BE803
primenet.py: submit_one_line_v5: server message: PRP result matches previously verified M8419067 --
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":8419069, "known-factors":["202057657","20528451676633","422159397443561"], "worktype":"PRP-3", "res64":"219D80D86619E719", "residue-type":5, "res2048":"63AB7616CDEC9D57F45596220DC7F26630D893415AECF53CDC763FCB278ED8B8650C1305CDB0F2E5BB7F388C954C6B1ADE69E030C025EB887FF8511A5F13AC5C013A0C590D3E0020E3ED27219F5D1F6224FCDBC17A38AB338F1C917F2A850F36641A2AB1CA164843FC0C414A2555215601977F76B7094C9BAF7B83EA954CB9A32D0971F88A7EF13D16033892128827ECA9DF6E790023F725A8584B6FC59F5176896F90620E265F026475F7BF57164D1C89610B07E41DD5FF851B4988025836458D0E3D3636C0FA1C1F78B7F0EE69C0FCF04708E4CD3100F89C92966ED11D089CAEA62CA525C1B69C65E2A021D94928E6CD78A9DF6C32CE41219D80D86619E719", "fft-length":458752, "shift-count":7644299, "error-code":"00000000", "security-code":"94598A0E", "program":{"name":"Prime95", "version":"29.8", "build":6, "port":8}, "timestamp":"2020-05-24 08:06:53", "errors":{"gerbicz":0}, "user":"llloic_test", "aid":"9B25DD00CFB7A5E823CFD702DA24D03D"}
primenet.py: submit_one_line_v5: ERROR while submitting result on mersenne.org: assignment_id=9B25DD00CFB7A5E823CFD702DA24D03D
primenet.py: submit_one_line_v5: ERROR UNREGISTERED CPU: Please remove guid line from local.ini, run with --register and retry
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":8419079, "known-factors":["17579036953"], "worktype":"PRP-3", "res64":"422FA7C9C6034FE3", "residue-type":5, "res2048":"65DF7A9F9FE61D8308C719CC53CCBB0C63BF0FD7B7E996A415CFB4C7333AB58AE18E3E53F0F64D27740AC3F6A2AF2217EEDCCAFC0F920327012D1426163F919BEDCE2BCDD835C4C474AB3FAE3A63CF763005ED426AA0FAFFAF5C67FC72516BD5A2A68E0AA926470222DD99825994B960C53F5C6C522AFFB6B344F1441C9FCD4A5B4A7487C07C467F9023296B706A59225E2747821C0D8CC4D87D5E29BA5C801D119F14CE7DEDBFF5F1D677B9B82F6F68E0704E40E095072E3A6D7754FE78689AD971A5F5C0DE5519A49D07E080FE37335569FA9AB6369161A87928EB768FDDFC63CDC3946B15DCE00E0C52FFCBB5AE4F7393E34045375923422FA7C9C6034FE3", "fft-length":458752, "shift-count":2591152, "error-code":"00000000", "security-code":"946D8A22", "program":{"name":"Prime95", "version":"29.8", "build":6, "port":8}, "timestamp":"2020-05-24 11:27:31", "errors":{"gerbicz":0}, "user":"ANONYMOUS", "aid":"6C4E9F3DF8DDB7C75973E9B7225FF7C0"}
primenet.py: submit_one_line_v5: ERROR while submitting result on mersenne.org: assignment_id=6C4E9F3DF8DDB7C75973E9B7225FF7C0
primenet.py: submit_one_line_v5: Reason: This computer has already sent in this PRP result for M8419079
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":10388359, "known-factors":["119922117290724673","3581852381888739001"], "worktype":"PRP-3", "res64":"A4B0A6F3FFFB8C74", "residue-type":5, "res2048":"D2AE789A2A29EE6EADB94629F08B6947F183E40F896B2B7B9C0ADB51507E0D76DE1C65476C8EA5BE0C495C43582F1AC676057EB4E56FB6DBE841255E0D785B2FFEF99C64C859C0D069E8F4E96E748FD65B99A5B670CD279DD13410781A087BAB5F2F0F2031B1BBC59E263558EA4026E7CD3D584F33C5D1D4EA4114C72722A83443AA86F3248653F22AA78073F6985A689CF19F3E4CEBFDB8C61269AB60A3D9B7E986074E89DDC2C66FD4C6796A62A56A2BDF63E3E9C69809CA06D8D5B031A68B5BBC5AD6600441D72C7D8D7D064B26C4CC0034EA84CAE1ADA615D4B9F1F6E2AAC93743C99A03FEEECD160CAB1919033E53CB3C257C9ACDA4A4B0A6F3FFFB8C74", "fft-length":573440, "shift-count":4935151, "error-code":"00000000", "security-code":"A49D230E", "program":{"name":"Prime95", "version":"29.8", "build":6, "port":8}, "timestamp":"2020-05-24 06:01:27", "errors":{"gerbicz":0}, "user":"ANONYMOUS", "aid":"6B36288BC4C6394962722EAB0949D8DC"}
primenet.py: submit_one_line_v5: ERROR while submitting result on mersenne.org: assignment_id=6B36288BC4C6394962722EAB0949D8DC
primenet.py: submit_one_line_v5: INVALID PARAMETER: this is a bug in primenet.py, please notify the author
primenet.py: submit_one_line_v5: Reason: invalid parameter
primenet.py: submit_one_line_v5: Submitting using V5 API
{"status":"C", "exponent":96365273, "worktype":"PRP-3", "res64":"99B5A59FF6ACA203", "residue-type":1, "fft-length":5242880, "shift-count":2468420, "error-code":"00000000", "program":{"name":"Mlucas", "version":"19.0"}, "timestamp":"2020-05-26 08:05:50 GMT", "aid":"62D4487DDFF26431DFB2F8950B4DCBA9"}
primenet.py: send_request: ERROR receiving answer to request: http://v5.mersenne.org/v5server/?px=GIMPS&v=0.95&t=ar&k=62D4487DDFF26431DFB2F8950B4DCBA9&m=%7B%22status%22%3A%22C%22%2C+%22exponent%22%3A96365273%2C+%22worktype%22%3A%22PRP-3%22%2C+%22res64%22%3A%2299B5A59FF6ACA203%22%2C+%22residue-type%22%3A1%2C+%22fft-length%22%3A5242880%2C+%22shift-count%22%3A2468420%2C+%22error-code%22%3A%2200000000%22%2C+%22program%22%3A%7B%22name%22%3A%22Mlucas%22%2C+%22version%22%3A%2219.0%22%7D%2C+%22timestamp%22%3A%222020-05-26+08%3A05%3A50+GMT%22%2C+%22aid%22%3A%2262D4487DDFF26431DFB2F8950B4DCBA9%22%7D&r=150&d=1&n=96365273&A=1&b=2&c=-1&rd=99B5A59FF6ACA203&ec=00000000&base=3&rt=1&sc=2468420&fftlen=5242880&g=07bd50dc0489bb4a44da5639df9889a8&ss=60027&sh=A7565B90ED2E4AE95731A51B380B98EC
primenet.py: send_request: HTTP Error 500: Server Error
primenet.py: submit_one_line_v5: ERROR while submitting result on mersenne.org: assignment_id=62D4487DDFF26431DFB2F8950B4DCBA9
primenet.py: get_assignment: ./worktodo.ini already has 0 >= 0 entries, not getting new work
